// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUIConcessionarioLauncher.h"
#include <FL/Fl.H>
#include <FL/fl_ask.H>
#include "GUITabboz.h"
#include "GUIScooter.h"
#include "../zarrosim.h"

Fl_Double_Window *win_conce_launcher=(Fl_Double_Window *)0;

static void cb_Back(Fl_Return_Button*, void*) {
  win_scooter->activate();
win_conce_launcher->hide();
}

static void cb_Scooter(Fl_Button*, void*) {
  //GUIConcessionarioMalagutty();
//win_conce_malagutty->show();
//win_conce_launcher->hide();
}

static void cb_Scooter1(Fl_Button*, void*) {
  //GUIConcessionarioMalagutty();
//win_conce_malagutty->show();
//win_conce_launcher->hide();
}

Fl_Double_Window* GUIConcessionarioLauncher() {
  { win_conce_launcher = new Fl_Double_Window(195, 135, "Concessionari");
    win_conce_launcher->color(FL_LIGHT3);
    win_conce_launcher->labelfont(1);
    win_conce_launcher->labelsize(12);
    win_conce_launcher->hotspot(win_conce_launcher);
    { Fl_Return_Button* o = new Fl_Return_Button(130, 80, 60, 50, "Back");
      o->callback((Fl_Callback*)cb_Back);
    } // Fl_Return_Button* o
    { Fl_Button* o = new Fl_Button(5, 5, 185, 30, "Scooter Malagutty");
      o->callback((Fl_Callback*)cb_Scooter);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(5, 40, 185, 30, "Scooter di altre marche");
      o->callback((Fl_Callback*)cb_Scooter1);
      o->deactivate();
    } // Fl_Button* o
    win_conce_launcher->set_modal();
    win_conce_launcher->size_range(195, 135, 195, 135);
    win_conce_launcher->end();
  } // Fl_Double_Window* win_conce_launcher
  return win_conce_launcher;
}
