// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUIConfig_h
#define GUIConfig_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_config;
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *cfg_euro;
extern Fl_Check_Button *cfg_timer;
extern Fl_Check_Button *cfg_suono;
extern Fl_Check_Button *cfg_log;
#include <FL/Fl_Button.H>
Fl_Double_Window* GUIConfig();
extern Fl_Menu_Item menu_Tema[];
extern Fl_Double_Window *win_about;
#include <FL/Fl_Box.H>
Fl_Double_Window* GUIAbout();
#endif
