// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUIConcessionarioLauncher_h
#define GUIConcessionarioLauncher_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_conce_launcher;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>
Fl_Double_Window* GUIConcessionarioLauncher();
#endif
