// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUIDisco_h
#define GUIDisco_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_disco;
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Browser.H>
extern Fl_Browser *disco_txtbox;
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *disco_val_soldi;
#include <FL/Fl_Button.H>
extern Fl_Button *disco_btn_ok;
#include <FL/Fl_Return_Button.H>
Fl_Double_Window* GUITabbozDisco();
#endif
