// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUIDisco.h"
#include "GUITabboz.h"
#include "../zarrosim.h"
#include "../sharedimg.h"
#include "../disco.h"
int disco_scelta=0; 

static void add_prezzo(int scelta) {
  static char buf[80];
  if(!euro)
    sprintf(buf, "Ingresso: L. %d",CALCSOLDI(DiscoMem[scelta].costo));
  else
    sprintf(buf, "Ingresso: € %d",CALCSOLDI(DiscoMem[scelta].costo));
  disco_txtbox->add(buf);
}

Fl_Double_Window *win_disco=(Fl_Double_Window *)0;

static void cb_Splush(Fl_Round_Button*, void*) {
  disco_txtbox->load("res/txt/disco1.txt");
disco_scelta=1;
disco_btn_ok->activate();
add_prezzo(disco_scelta);
win_disco->redraw();
}

static void cb_QB(Fl_Round_Button*, void*) {
  disco_txtbox->load("res/txt/disco2.txt");
disco_scelta=2;
disco_btn_ok->activate();
add_prezzo(disco_scelta);
win_disco->redraw();
}

static void cb_Spoking(Fl_Round_Button*, void*) {
  disco_txtbox->load("res/txt/disco3.txt");
disco_scelta=3;
disco_btn_ok->activate();
add_prezzo(disco_scelta);
win_disco->redraw();
}

static void cb_Madame(Fl_Round_Button*, void*) {
  disco_txtbox->load("res/txt/disco4.txt");
disco_scelta=4;
disco_btn_ok->activate();
add_prezzo(disco_scelta);
win_disco->redraw();
}

static void cb_Number(Fl_Round_Button*, void*) {
  disco_txtbox->load("res/txt/disco5.txt");
disco_scelta=5;
disco_btn_ok->activate();
add_prezzo(disco_scelta);
win_disco->redraw();
}

static void cb_Spuce(Fl_Round_Button*, void*) {
  disco_txtbox->load("res/txt/disco6.txt");
disco_scelta=6;
disco_btn_ok->activate();
add_prezzo(disco_scelta);
win_disco->redraw();
}

static void cb_Honeywood(Fl_Round_Button*, void*) {
  disco_txtbox->load("res/txt/disco7.txt");
disco_scelta=7;
disco_btn_ok->activate();
add_prezzo(disco_scelta);
win_disco->redraw();
}

static void cb_Strap(Fl_Round_Button*, void*) {
  disco_txtbox->load("res/txt/disco8.txt");
disco_scelta=8;
disco_btn_ok->activate();
add_prezzo(disco_scelta);
win_disco->redraw();
}

Fl_Browser *disco_txtbox=(Fl_Browser *)0;

Fl_Value_Output *disco_val_soldi=(Fl_Value_Output *)0;

static void cb_disco_val_soldi(Fl_Value_Output* o, void*) {
  o->value(CALCSOLDI(Soldi));
}

Fl_Button *disco_btn_ok=(Fl_Button *)0;

static void cb_disco_btn_ok(Fl_Button*, void*) {
  PagaDisco(disco_scelta);
win_principale->activate();
AggiornaPrincipale();
win_disco->hide();
disco_scelta=0;
}

static void cb_(Fl_Return_Button*, void*) {
  win_principale->activate();
AggiornaPrincipale();
win_disco->hide();
disco_scelta=0;
}

Fl_Double_Window* GUITabbozDisco() {
  { win_disco = new Fl_Double_Window(485, 290, "Disco");
    win_disco->hotspot(win_disco);
    { Fl_Group* o = new Fl_Group(5, 5, 160, 225);
      o->box(FL_EMBOSSED_FRAME);
      { Fl_Round_Button* o = new Fl_Round_Button(10, 10, 150, 20, "Splush");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->callback((Fl_Callback*)cb_Splush);
        o->when(FL_WHEN_CHANGED);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 37, 150, 20, "QB");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->callback((Fl_Callback*)cb_QB);
        o->when(FL_WHEN_CHANGED);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 65, 150, 20, "Spoking");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->callback((Fl_Callback*)cb_Spoking);
        o->when(FL_WHEN_CHANGED);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 93, 150, 20, "Madame Close");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->callback((Fl_Callback*)cb_Madame);
        o->when(FL_WHEN_CHANGED);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 121, 150, 20, "Number 0");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->callback((Fl_Callback*)cb_Number);
        o->when(FL_WHEN_CHANGED);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 149, 150, 20, "Spuce");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->callback((Fl_Callback*)cb_Spuce);
        o->when(FL_WHEN_CHANGED);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 177, 150, 20, "Honeywood");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->callback((Fl_Callback*)cb_Honeywood);
        o->when(FL_WHEN_CHANGED);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 205, 150, 20, "Strap Line");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->callback((Fl_Callback*)cb_Strap);
        o->when(FL_WHEN_CHANGED);
      } // Fl_Round_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Browser* o = disco_txtbox = new Fl_Browser(165, 5, 315, 225);
      disco_txtbox->box(FL_EMBOSSED_FRAME);
      o->add("\n\n\n\n\n    A che disco andiamo?",0);
    } // Fl_Browser* disco_txtbox
    { Fl_Group* o = new Fl_Group(5, 235, 475, 50);
      o->box(FL_EMBOSSED_FRAME);
      o->labelsize(10);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      { Fl_Value_Output* o = disco_val_soldi = new Fl_Value_Output(65, 247, 80, 25, "Soldi L. ");
        disco_val_soldi->box(FL_EMBOSSED_BOX);
        disco_val_soldi->color(FL_BACKGROUND2_COLOR);
        disco_val_soldi->selection_color(FL_BACKGROUND2_COLOR);
        disco_val_soldi->labelsize(12);
        disco_val_soldi->maximum(0);
        disco_val_soldi->step(1);
        disco_val_soldi->value(1e+08);
        disco_val_soldi->textfont(5);
        disco_val_soldi->callback((Fl_Callback*)cb_disco_val_soldi);
        o->value(CALCSOLDI(Soldi));
      } // Fl_Value_Output* disco_val_soldi
      { Fl_Button* o = disco_btn_ok = new Fl_Button(345, 240, 60, 40, "OK!");
        disco_btn_ok->callback((Fl_Callback*)cb_disco_btn_ok);
        if(!disco_scelta) o->deactivate();
      } // Fl_Button* disco_btn_ok
      { Fl_Return_Button* o = new Fl_Return_Button(415, 240, 60, 40);
        o->callback((Fl_Callback*)cb_);
        o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
        o->image(ImgExit);
      } // Fl_Return_Button* o
      o->end();
    } // Fl_Group* o
    win_disco->set_modal();
    win_disco->size_range(485, 290, 485, 290);
    win_disco->end();
  } // Fl_Double_Window* win_disco
  return win_disco;
}
