// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUIEvento_h
#define GUIEvento_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_evento_v;
#include <FL/Fl_Box.H>
#include <FL/Fl_Return_Button.H>
extern "C" { Fl_Double_Window* GUIEventoVert(int img_evento, char *txt_evento); }
extern Fl_Double_Window *win_evento_o;
extern "C" { Fl_Double_Window* GUIEventoOriz(int img_evento, char *txt_evento); }
#endif
