// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUIElaborare_h
#define GUIElaborare_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_elabora;
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Output.H>
extern Fl_Output *elabora_txt_marm;
#include <FL/Fl_Choice.H>
extern Fl_Choice *elabora_menu_marm;
#include <FL/Fl_Button.H>
extern Fl_Button *elabora_btn_compra_marm;
extern Fl_Output *elabora_txt_prezzo_marm;
extern Fl_Output *elabora_txt_filtro;
extern Fl_Choice *elabora_menu_filtro;
extern Fl_Button *elabora_btn_compra_filtro;
extern Fl_Output *elabora_txt_prezzo_filtro;
extern Fl_Output *elabora_txt_carb;
extern Fl_Choice *elabora_menu_carb;
extern Fl_Button *elabora_btn_compra_carb;
extern Fl_Output *elabora_txt_prezzo_carb;
extern Fl_Output *elabora_txt_cc;
extern Fl_Choice *elabora_menu_cc;
extern Fl_Button *elabora_btn_compra_cc;
extern Fl_Output *elabora_txt_prezzo_cc;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *elabora_soldi;
#include <FL/Fl_Return_Button.H>
extern Fl_Output *elabora_txt_speed;
Fl_Double_Window* GUIElaborare();
extern Fl_Menu_Item menu_elabora_menu_marm[];
extern Fl_Menu_Item menu_elabora_menu_filtro[];
extern Fl_Menu_Item menu_elabora_menu_carb[];
extern Fl_Menu_Item menu_elabora_menu_cc[];
#endif
