// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUIFamiglia.h"
#include "GUITabboz.h"
#include "../zarrosim.h"
#include "../famiglia.h"

Fl_Double_Window *win_famiglia=(Fl_Double_Window *)0;

static void cb_OK(Fl_Return_Button*, void*) {
  win_principale->show();
AggiornaPrincipale();
win_famiglia->hide();
}

static void cb_Chiedi(Fl_Button*, void*) {
  ChiediAumentoPaghetta();
}

static void cb_Chiedi1(Fl_Button*, void*) {
  ChiediSoldiExtra();
}

static void cb_Pap(Fl_Button*, void*) {
  ChiediSoldiPapa();
}

Fl_Value_Output *fam_val_soldi=(Fl_Value_Output *)0;

Fl_Value_Output *fam_val_paghetta=(Fl_Value_Output *)0;

Fl_Double_Window* GUITabbozFamiglia() {
  { win_famiglia = new Fl_Double_Window(550, 330, "Famiglia");
    win_famiglia->color(FL_LIGHT3);
    { Fl_Return_Button* o = new Fl_Return_Button(480, 260, 60, 60, "OK");
      o->callback((Fl_Callback*)cb_OK);
    } // Fl_Return_Button* o
    { Fl_Button* o = new Fl_Button(10, 100, 530, 35, "Chiedi aumento paghetta");
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->callback((Fl_Callback*)cb_Chiedi);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(10, 140, 530, 35, "Chiedi soldi extra");
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->callback((Fl_Callback*)cb_Chiedi1);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(10, 180, 530, 35, "Pap\303\240, mi dai 100.000 lire?");
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->callback((Fl_Callback*)cb_Pap);
      if(euro) o->label("Papà, mi dai 50€ ?");
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(10, 265, 405, 45);
      o->box(FL_ENGRAVED_FRAME);
      o->labelsize(10);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      { Fl_Value_Output* o = fam_val_soldi = new Fl_Value_Output(65, 275, 120, 25, "Soldi  L.");
        fam_val_soldi->color(FL_BACKGROUND2_COLOR);
        fam_val_soldi->labelsize(12);
        o->value(CALCSOLDI(Soldi));
        if(euro) o->label("Soldi  €");
      } // Fl_Value_Output* fam_val_soldi
      { Fl_Value_Output* o = fam_val_paghetta = new Fl_Value_Output(305, 275, 100, 25, "Paghetta  L.");
        fam_val_paghetta->color(FL_BACKGROUND2_COLOR);
        fam_val_paghetta->labelsize(12);
        o->value(CALCSOLDI(Paghetta));
        if(euro) o->label("Paghetta  €");
      } // Fl_Value_Output* fam_val_paghetta
      o->end();
    } // Fl_Group* o
    win_famiglia->size_range(550, 330, 550, 330);
    win_famiglia->end();
  } // Fl_Double_Window* win_famiglia
  return win_famiglia;
}
