// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUIFamiglia.h"
#include "GUITabboz.h"
#include "../zarrosim.h"
#include "../famiglia.h"

Fl_Double_Window *win_famiglia=(Fl_Double_Window *)0;

static void cb_Chiedi(Fl_Button*, void*) {
  ChiediAumentoPaghetta();
}

static void cb_Chiedi1(Fl_Button*, void*) {
  ChiediSoldiExtra();
}

static void cb_Pap(Fl_Button*, void*) {
  ChiediSoldiPapa();
}

Fl_Value_Output *fam_val_soldi=(Fl_Value_Output *)0;

Fl_Value_Output *fam_val_paghetta=(Fl_Value_Output *)0;

static void cb_OK(Fl_Return_Button*, void*) {
  win_principale->activate();
AggiornaPrincipale();
win_famiglia->hide();
}

Fl_Double_Window* GUITabbozFamiglia() {
  { win_famiglia = new Fl_Double_Window(415, 330, "Famiglia");
    win_famiglia->color(FL_LIGHT3);
    win_famiglia->hotspot(win_famiglia);
    { Fl_Box* o = new Fl_Box(10, 5, 395, 140, "immagine casa");
      o->box(FL_ENGRAVED_FRAME);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(10, 155, 395, 30, "Chiedi aumento paghetta");
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->callback((Fl_Callback*)cb_Chiedi);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(10, 190, 395, 30, "Chiedi soldi extra");
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->callback((Fl_Callback*)cb_Chiedi1);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(10, 225, 395, 30, "Pap\303\240, mi dai 100.000 lire?");
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->callback((Fl_Callback*)cb_Pap);
      if(euro) o->label("Papà, mi dai 50€ ?");
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(10, 265, 330, 50);
      o->box(FL_ENGRAVED_FRAME);
      o->labelsize(10);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      { Fl_Value_Output* o = fam_val_soldi = new Fl_Value_Output(65, 277, 105, 25, "Soldi  L.");
        fam_val_soldi->color(FL_BACKGROUND2_COLOR);
        fam_val_soldi->labelsize(12);
        fam_val_soldi->step(1);
        o->value(CALCSOLDI(Soldi));
        if(euro) o->label("Soldi  €");
      } // Fl_Value_Output* fam_val_soldi
      { Fl_Value_Output* o = fam_val_paghetta = new Fl_Value_Output(250, 278, 80, 23, "Paghetta  L.");
        fam_val_paghetta->color(FL_BACKGROUND2_COLOR);
        fam_val_paghetta->labelsize(12);
        fam_val_paghetta->step(1);
        o->value(CALCSOLDI(Paghetta));
        if(euro) o->label("Paghetta  €");
      } // Fl_Value_Output* fam_val_paghetta
      o->end();
    } // Fl_Group* o
    { Fl_Return_Button* o = new Fl_Return_Button(345, 265, 60, 50, "OK");
      o->callback((Fl_Callback*)cb_OK);
    } // Fl_Return_Button* o
    win_famiglia->set_modal();
    win_famiglia->size_range(415, 330, 415, 330);
    win_famiglia->end();
  } // Fl_Double_Window* win_famiglia
  return win_famiglia;
}
