// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUINegozioVestiti1.h"
#include "GUITabboz.h"
#include "GUINegoziLauncher.h"
#include "../zarrosim.h"
#include "../negozi.h"
#include "../sharedimg.h"
int scelta=0; 
char buf[80]; 

static void add_prezzo(int scelta) {
  if(!euro)
    sprintf(buf, "Prezzo: L. %d",CALCSOLDI(VestitiMem[scelta].prezzo));
  else
    sprintf(buf, "Prezzo: € %d",CALCSOLDI(VestitiMem[scelta].prezzo));
  boxtxt_vestiti->add(buf);
}

Fl_Double_Window *win_vestiti_1=(Fl_Double_Window *)0;

Fl_Button *neg1_btn_1=(Fl_Button *)0;

static void cb_neg1_btn_1(Fl_Button* o, void*) {
  scelta=1;
o->image(ImgGiubbotto[scelta]);
giub_colore->activate();
giub_colore->value(0);
boxtxt_vestiti->clear();
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("@bGiubbotto \"Fatiscenza\"");
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("Elegante e raffinato, adatto a tutte le occasioni,");
boxtxt_vestiti->add("dalle serate con gli amici alle feste più esclusive.");
boxtxt_vestiti->add(NULL);
add_prezzo(scelta);
win_vestiti_1->redraw();
neg1_btn_compra->activate();
}

static void cb_(Fl_Button*, void*) {
  scelta=5;
boxtxt_vestiti->clear();
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("@bGiubbotto di pelle");
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("Giacca di pelle...");
boxtxt_vestiti->add("cos'altro dire?");
giub_colore->deactivate();
boxtxt_vestiti->add(NULL);
add_prezzo(scelta);
win_vestiti_1->redraw();
neg1_btn_compra->activate();
}

static void cb_1(Fl_Button*, void*) {
  scelta=6;
boxtxt_vestiti->clear();
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("@bCappotto con pelliccia fluo");
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("Ecco qualcosa per i più ricercati!");
boxtxt_vestiti->add("Come può mancare nell'armadio un vestito come questo?");
boxtxt_vestiti->add("Compratelo subito, non ve ne pentirete.");
giub_colore->deactivate();
boxtxt_vestiti->add(NULL);
add_prezzo(scelta);
win_vestiti_1->redraw();
neg1_btn_compra->activate();
}

Fl_Choice *giub_colore=(Fl_Choice *)0;

static void cb_Original(Fl_Menu_*, void*) {
  scelta=1;
neg1_btn_1->image(ImgGiubbotto[scelta]);
boxtxt_vestiti->clear();
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("@bGiubbotto \"Fatiscenza\"");
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("Elegante e raffinato, adatto a tutte le occasioni,");
boxtxt_vestiti->add("dalle serate con gli amici alle feste più esclusive.");
boxtxt_vestiti->add(NULL);
add_prezzo(scelta);
win_vestiti_1->redraw();
}

static void cb_Silver(Fl_Menu_*, void*) {
  scelta=2;
neg1_btn_1->image(ImgGiubbotto[scelta]);
boxtxt_vestiti->clear();
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("@bGiubbotto \"Fatiscenza\"");
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("Nuova collezione, per essere sempre in linea");
boxtxt_vestiti->add("con i tempi che cambiano. Colore \"Silver\"");
boxtxt_vestiti->add(NULL);
add_prezzo(scelta);
win_vestiti_1->redraw();
}

static void cb_Green(Fl_Menu_*, void*) {
  scelta=3;
neg1_btn_1->image(ImgGiubbotto[scelta]);
boxtxt_vestiti->clear();
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("@bGiubbotto \"Fatiscenza\"");
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("Nuova collezione, per essere sempre in linea");
boxtxt_vestiti->add("con i tempi che cambiano. Colore \"Acid Green\"");
boxtxt_vestiti->add(NULL);
add_prezzo(scelta);
win_vestiti_1->redraw();
}

static void cb_White(Fl_Menu_*, void*) {
  scelta=4;
neg1_btn_1->image(ImgGiubbotto[scelta]);
boxtxt_vestiti->clear();
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("@bGiubbotto \"Fatiscenza\"");
boxtxt_vestiti->add(NULL);
boxtxt_vestiti->add("Versione \"White\", con una comoda imbottitura");
boxtxt_vestiti->add("in piumino sintetico, è adatto a tutte le stagioni.");
boxtxt_vestiti->add(NULL);
add_prezzo(scelta);
win_vestiti_1->redraw();
}

Fl_Menu_Item menu_giub_colore[] = {
 {"Original Blue", 0,  (Fl_Callback*)cb_Original, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 12, 0},
 {"Silver", 0,  (Fl_Callback*)cb_Silver, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 12, 0},
 {"Green Line", 0,  (Fl_Callback*)cb_Green, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 12, 0},
 {"White", 0,  (Fl_Callback*)cb_White, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 12, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Browser *boxtxt_vestiti=(Fl_Browser *)0;

Fl_Button *neg1_btn_compra=(Fl_Button *)0;

static void cb_neg1_btn_compra(Fl_Button*, void*) {
  PagaQualcosa(scelta);
win_principale->activate();
AggiornaPrincipale();
win_vestiti_1->hide();
}

static void cb_2(Fl_Return_Button*, void*) {
  win_negozi->show();
win_vestiti_1->hide();
}

static void cb_Soldi(Fl_Value_Output* o, void*) {
  o->value(CALCSOLDI(Soldi));
}

static void cb_Figosit(Fl_Value_Output* o, void*) {
  o->value(Fama);
}

Fl_Double_Window* GUINegozioVestiti_1() {
  { win_vestiti_1 = new Fl_Double_Window(580, 320, "Bau House");
    win_vestiti_1->labelfont(1);
    win_vestiti_1->labelsize(12);
    win_vestiti_1->hotspot(win_vestiti_1);
    { Fl_Group* o = new Fl_Group(10, 10, 560, 150);
      { Fl_Button* o = neg1_btn_1 = new Fl_Button(10, 10, 180, 120);
        neg1_btn_1->type(102);
        neg1_btn_1->color(FL_BACKGROUND2_COLOR);
        neg1_btn_1->selection_color((Fl_Color)3);
        neg1_btn_1->callback((Fl_Callback*)cb_neg1_btn_1);
        o->image(ImgGiubbotto[1]);
      } // Fl_Button* neg1_btn_1
      { Fl_Button* o = new Fl_Button(200, 10, 180, 120);
        o->type(102);
        o->color(FL_BACKGROUND2_COLOR);
        o->selection_color((Fl_Color)3);
        o->callback((Fl_Callback*)cb_);
        o->image(ImgGiubbotto[5]);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(390, 10, 180, 120);
        o->type(102);
        o->color(FL_BACKGROUND2_COLOR);
        o->selection_color((Fl_Color)3);
        o->callback((Fl_Callback*)cb_1);
        o->image(ImgGiubbotto[6]);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Choice* o = giub_colore = new Fl_Choice(10, 135, 180, 20);
      giub_colore->down_box(FL_BORDER_BOX);
      giub_colore->menu(menu_giub_colore);
      o->deactivate();
    } // Fl_Choice* giub_colore
    { boxtxt_vestiti = new Fl_Browser(10, 165, 380, 140);
      boxtxt_vestiti->box(FL_EMBOSSED_FRAME);
      boxtxt_vestiti->color(FL_LIGHT3);
      boxtxt_vestiti->when(FL_WHEN_NEVER);
    } // Fl_Browser* boxtxt_vestiti
    { Fl_Group* o = new Fl_Group(400, 165, 170, 140);
      o->box(FL_EMBOSSED_FRAME);
      { Fl_Button* o = neg1_btn_compra = new Fl_Button(405, 260, 60, 40, "Compra!");
        neg1_btn_compra->callback((Fl_Callback*)cb_neg1_btn_compra);
        o->deactivate();
      } // Fl_Button* neg1_btn_compra
      { Fl_Return_Button* o = new Fl_Return_Button(505, 260, 60, 40);
        o->callback((Fl_Callback*)cb_2);
        o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
        o->image(ImgExit);
      } // Fl_Return_Button* o
      { Fl_Value_Output* o = new Fl_Value_Output(470, 170, 80, 25, "Soldi L.");
        o->box(FL_EMBOSSED_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->selection_color(FL_BACKGROUND2_COLOR);
        o->labelsize(12);
        o->step(1);
        o->textfont(5);
        o->callback((Fl_Callback*)cb_Soldi);
        o->value(CALCSOLDI(Soldi));
        if(euro) o->label("Soldi  €");
      } // Fl_Value_Output* o
      { Fl_Value_Output* o = new Fl_Value_Output(470, 200, 35, 25, "Figosit\303\240");
        o->box(FL_EMBOSSED_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->selection_color(FL_BACKGROUND2_COLOR);
        o->labelsize(12);
        o->value(100);
        o->callback((Fl_Callback*)cb_Figosit);
        o->value(Fama);
      } // Fl_Value_Output* o
      { new Fl_Box(505, 204, 15, 16, "%");
      } // Fl_Box* o
      o->end();
    } // Fl_Group* o
    win_vestiti_1->set_modal();
    win_vestiti_1->size_range(580, 320, 580, 320);
    win_vestiti_1->end();
  } // Fl_Double_Window* win_vestiti_1
  return win_vestiti_1;
}
