// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUINegoziLauncher_h
#define GUINegoziLauncher_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_negozi;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
Fl_Double_Window* GUINegoziLauncher();
#endif
