// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUINegoziLauncher.h"
#include <FL/Fl.H>
#include <FL/fl_ask.H>
#include "GUITabboz.h"
#include "GUINegoziVestiti.h"
#include "GUITabacchi.h"
#include "GUITelefonia.h"
#include "../zarrosim.h"
#include "../dialogs.h"
#include "../sound.h"
#include "../sharedimg.h"
#include "../calendario.h"
#include "../negozi.h"

Fl_Double_Window *win_negozi=(Fl_Double_Window *)0;

static void cb_(Fl_Return_Button*, void*) {
  win_principale->activate();
win_negozi->hide();
}

static void cb_Bau(Fl_Button*, void*) {
  if (x_vacanza != 2) {
  GUINegoziVestiti_1();
  win_vestiti_1->show();
  if(sound_active) TabbozPlaySound(204);
}else {
  MsgIcona(ICONA_AVVISO);
  fl_message_title("Negozio chiuso");
  fl_alert("Oh, tip%c... i negozi sono chiusi di festa...",ao);
};
}

static void cb_Blue(Fl_Button*, void*) {
  if (x_vacanza != 2) {
  GUINegoziVestiti_2();
  win_vestiti_2->show();
  if(sound_active) TabbozPlaySound(204);
}else {
  MsgIcona(ICONA_AVVISO);
  fl_message_title("Negozio chiuso");
  fl_alert("Oh, tip%c... i negozi sono chiusi di festa...",ao);
};
}

static void cb_Footsmocker(Fl_Button*, void*) {
  if (x_vacanza != 2) {
  GUINegoziVestiti_3();
  win_vestiti_3->show();
  if(sound_active) TabbozPlaySound(204);
}else {
  MsgIcona(ICONA_AVVISO);
  fl_message_title("Negozio chiuso");
  fl_alert("Oh, tip%c... i negozi sono chiusi di festa...",ao);
};
}

static void cb_Tabaccaio(Fl_Button*, void*) {
  if (x_vacanza != 2) {
  GUITabacchi();
  win_tabacchi->show();
  if(sound_active) TabbozPlaySound(203);
}else {
  MsgIcona(ICONA_AVVISO);
  fl_message_title("Tabaccaio chiuso");
  fl_alert("Rimani fiss%c a guardare la saracinesca del tabaccaio irrimediabilmente chiusa...",ao);
};
}

static void cb_Telefonia(Fl_Button*, void*) {
  GUITelefonia();
win_telefonia->show();
}

Fl_Double_Window* GUINegoziLauncher() {
  { win_negozi = new Fl_Double_Window(395, 161, "Negozi");
    win_negozi->labelfont(1);
    win_negozi->labelsize(12);
    win_negozi->hotspot(win_negozi);
    { Fl_Return_Button* o = new Fl_Return_Button(320, 110, 60, 40);
      o->shortcut(0xff1b);
      o->callback((Fl_Callback*)cb_);
      o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      o->image(ImgExit);
    } // Fl_Return_Button* o
    { Fl_Group* o = new Fl_Group(10, 25, 180, 110, "Abbigliamento");
      o->box(FL_EMBOSSED_FRAME);
      o->labelfont(1);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      { Fl_Button* o = new Fl_Button(15, 30, 170, 30, "Bau House");
        o->callback((Fl_Callback*)cb_Bau);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(15, 65, 170, 30, "Blue Rider");
        o->callback((Fl_Callback*)cb_Blue);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(15, 100, 170, 30, "Footsmocker");
        o->callback((Fl_Callback*)cb_Footsmocker);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(200, 25, 180, 75, "Altri Negozi");
      o->box(FL_EMBOSSED_FRAME);
      o->labelfont(1);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      { Fl_Button* o = new Fl_Button(205, 30, 170, 30, "Tabaccaio");
        o->callback((Fl_Callback*)cb_Tabaccaio);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(205, 65, 170, 30, "Telefonia");
        o->callback((Fl_Callback*)cb_Telefonia);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    win_negozi->set_modal();
    win_negozi->size_range(395, 161, 395, 161);
    win_negozi->end();
  } // Fl_Double_Window* win_negozi
  return win_negozi;
}
