// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUINegozioVestiti1_h
#define GUINegozioVestiti1_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_vestiti_1;
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Choice.H>
extern Fl_Choice *giub_colore;
#include <FL/Fl_Browser.H>
extern Fl_Browser *boxtxt_vestiti;
extern Fl_Button *neg1_btn_compra;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Value_Output.H>
Fl_Double_Window* GUINegozioVestiti_1();
extern Fl_Menu_Item menu_giub_colore[];
#endif
