// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUINegoziVestiti_h
#define GUINegoziVestiti_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_vestiti_1;
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern Fl_Button *neg1_btn_1;
#include <FL/Fl_Choice.H>
extern Fl_Choice *giub_colore;
#include <FL/Fl_Box.H>
extern Fl_Box *neg1_txt_nomegiub;
extern Fl_Box *neg1_txt_descgiub;
extern Fl_Box *neg1_txt_prezzogiub;
extern Fl_Button *neg1_btn_compra;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Value_Output.H>
Fl_Double_Window* GUINegoziVestiti_1();
extern Fl_Menu_Item menu_giub_colore[];
extern Fl_Double_Window *win_vestiti_2;
extern Fl_Button *neg2_btn_1;
extern Fl_Button *neg2_btn_4;
extern Fl_Choice *panta_colore;
extern Fl_Box *neg2_txt_nomepanta;
extern Fl_Box *neg2_txt_descpanta;
extern Fl_Box *neg2_txt_prezzopanta;
extern Fl_Button *neg2_btn_compra;
Fl_Double_Window* GUINegoziVestiti_2();
extern Fl_Menu_Item menu_panta_colore[];
extern Fl_Double_Window *win_vestiti_3;
extern Fl_Button *neg3_btn_1;
extern Fl_Button *neg3_btn_2;
extern Fl_Button *neg3_btn_3;
extern Fl_Choice *neg3_scarpe1_colore;
extern Fl_Choice *neg3_scarpe2_colore;
extern Fl_Choice *neg3_scarpe3_colore;
extern Fl_Box *neg3_txt_nomescarpe;
extern Fl_Box *neg3_txt_descscarpe;
extern Fl_Box *neg3_txt_prezzoscarpe;
extern Fl_Button *neg3_btn_compra;
Fl_Double_Window* GUINegoziVestiti_3();
extern Fl_Menu_Item menu_neg3_scarpe1_colore[];
#define neg3_scarpe1_menu (menu_neg3_scarpe1_colore+0)
extern Fl_Menu_Item menu_neg3_scarpe2_colore[];
extern Fl_Menu_Item menu_neg3_scarpe3_colore[];
#endif
