// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUIPalestra_h
#define GUIPalestra_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_palestra;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Output.H>
extern Fl_Output *pal_txtscadenza;
extern Fl_Output *pal_txtfaccia;
extern Fl_Value_Output *pal_soldi;
extern Fl_Value_Output *pal_fama;
Fl_Double_Window* GUITabbozPalestra();
#endif
