// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUIScooter.h"
#include <FL/Fl.H>
#include <FL/fl_ask.H>
#include "GUITabboz.h"
#include "GUIConcessionario.h"
#include "../zarrosim.h"
#include "../calendario.h"
#include "../sound.h"

Fl_Double_Window *win_scooter=(Fl_Double_Window *)0;

static void cb_Concessionario(Fl_Button*, void*) {
  if (x_vacanza != 2) {
  GUIConcessionario();
  win_conce->show();
  win_scooter->deactivate();
}else {
  fl_message_title("Concessionario chiuso");
  fl_alert("Oh, tip%c... oggi il concessionario è chiuso...",ao);
};
}

static void cb_Back(Fl_Return_Button*, void*) {
  win_principale->activate();
win_scooter->hide();
}

Fl_Output *sco_txtnome=(Fl_Output *)0;

Fl_Double_Window* GUIScooter() {
  { win_scooter = new Fl_Double_Window(510, 250, "Scooter");
    win_scooter->color(FL_LIGHT3);
    win_scooter->labelfont(1);
    win_scooter->labelsize(12);
    win_scooter->hotspot(win_scooter);
    { Fl_Button* o = new Fl_Button(10, 20, 240, 35, "Concessionario");
      o->callback((Fl_Callback*)cb_Concessionario);
    } // Fl_Button* o
    { Fl_Return_Button* o = new Fl_Return_Button(190, 190, 60, 50, "Back");
      o->callback((Fl_Callback*)cb_Back);
    } // Fl_Return_Button* o
    { new Fl_Button(10, 95, 240, 35, "Parcheggia/Usa scooter");
    } // Fl_Button* o
    { new Fl_Button(10, 135, 240, 35, "Fai benza");
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(260, 20, 240, 150, "Parametri Scooter");
      o->box(FL_EMBOSSED_FRAME);
      o->labelfont(1);
      o->labelsize(12);
      o->end();
    } // Fl_Group* o
    { new Fl_Button(260, 175, 240, 30, "Elabora Scooter");
    } // Fl_Button* o
    { new Fl_Button(260, 210, 240, 30, "Ripara Scooter");
    } // Fl_Button* o
    { new Fl_Output(340, 65, 150, 25, "Velocit\303\240   ");
    } // Fl_Output* o
    { new Fl_Output(340, 90, 150, 25, "Cilindrata ");
    } // Fl_Output* o
    { new Fl_Output(340, 115, 150, 25, "Efficienza ");
    } // Fl_Output* o
    { new Fl_Output(340, 140, 150, 25, "Benzina   ");
    } // Fl_Output* o
    { sco_txtnome = new Fl_Output(270, 30, 220, 25);
      sco_txtnome->box(FL_NO_BOX);
    } // Fl_Output* sco_txtnome
    win_scooter->set_modal();
    win_scooter->size_range(510, 250, 510, 250);
    win_scooter->end();
  } // Fl_Double_Window* win_scooter
  return win_scooter;
}
