// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUIScuola.h"
int materia_selezionata; 
#include "GUITabboz.h"
#include "../zarrosim.h"
#include "../scuola.h"

Fl_Double_Window *win_scuola=(Fl_Double_Window *)0;

static void cb_OK(Fl_Return_Button*, void*) {
  win_principale->show();
AggiornaPrincipale();
win_scuola->hide();
}

static void cb_Studia(Fl_Button*, void*) {
  StudiaMateria(materia_selezionata);
}

static void cb_Corrompi(Fl_Button*, void*) {
  CorrompiProf(materia_selezionata);
}

static void cb_Minaccia(Fl_Button*, void*) {
  MinacciaSeduciProf(materia_selezionata);
}

static void cb_Agraria(Fl_Round_Button*, void*) {
  materia_selezionata=1;
}

static void cb_Fisica(Fl_Round_Button*, void*) {
  materia_selezionata=2;
}

static void cb_Attivit(Fl_Round_Button*, void*) {
  materia_selezionata=3;
}

static void cb_Attivit1(Fl_Round_Button*, void*) {
  materia_selezionata=4;
}

static void cb_Scienze(Fl_Round_Button*, void*) {
  materia_selezionata=5;
}

static void cb_Elettrochimica(Fl_Round_Button*, void*) {
  materia_selezionata=6;
}

static void cb_Petrolchimica(Fl_Round_Button*, void*) {
  materia_selezionata=7;
}

static void cb_Filosofia(Fl_Round_Button*, void*) {
  materia_selezionata=8;
}

static void cb_Metallurgia(Fl_Round_Button*, void*) {
  materia_selezionata=9;
}

Fl_Group *grp_voti=(Fl_Group *)0;

Fl_Value_Output *val_voto1=(Fl_Value_Output *)0;

Fl_Value_Output *val_voto2=(Fl_Value_Output *)0;

Fl_Value_Output *val_voto3=(Fl_Value_Output *)0;

Fl_Value_Output *val_voto4=(Fl_Value_Output *)0;

Fl_Value_Output *val_voto5=(Fl_Value_Output *)0;

Fl_Value_Output *val_voto6=(Fl_Value_Output *)0;

Fl_Value_Output *val_voto7=(Fl_Value_Output *)0;

Fl_Value_Output *val_voto8=(Fl_Value_Output *)0;

Fl_Value_Output *val_voto9=(Fl_Value_Output *)0;

Fl_Value_Output *scuola_val_media=(Fl_Value_Output *)0;

Fl_Group *grp_barrastato=(Fl_Group *)0;

Fl_Value_Output *scuola_val_soldi=(Fl_Value_Output *)0;

Fl_Value_Output *scuola_val_rep=(Fl_Value_Output *)0;

Fl_Value_Output *scuola_val_studio=(Fl_Value_Output *)0;

Fl_Double_Window* GUITabbozScuola() {
  { win_scuola = new Fl_Double_Window(550, 345, "Scuola");
    win_scuola->color(FL_LIGHT3);
    { Fl_Return_Button* o = new Fl_Return_Button(480, 275, 60, 60, "OK");
      o->callback((Fl_Callback*)cb_OK);
    } // Fl_Return_Button* o
    { Fl_Button* o = new Fl_Button(270, 170, 270, 20, "Studia");
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->callback((Fl_Callback*)cb_Studia);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(270, 195, 270, 20, "Corrompi");
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->callback((Fl_Callback*)cb_Corrompi);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(270, 220, 270, 20, "Minaccia");
      o->color((Fl_Color)51);
      o->selection_color((Fl_Color)51);
      o->callback((Fl_Callback*)cb_Minaccia);
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(10, 10, 245, 270);
      o->box(FL_SHADOW_BOX);
      o->color(FL_BACKGROUND2_COLOR);
      { Fl_Round_Button* o = new Fl_Round_Button(12, 20, 215, 15, "Agraria.................");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Agraria);
        o->set();
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 44, 215, 15, "Fisica..................");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Fisica);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 68, 215, 15, "Attivit\303\240 Culturali......");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Attivit);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 93, 215, 15, "Attivit\303\240 Matematiche....");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Attivit1);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 117, 215, 15, "Scienze Industriali.....");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Scienze);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 141, 215, 15, "Elettrochimica..........");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Elettrochimica);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 166, 215, 15, "Petrolchimica...........");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Petrolchimica);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 190, 215, 15, "Filosofia Aziendale.....");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Filosofia);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 215, 215, 15, "Metallurgia.............");
        o->type(102);
        o->down_box(FL_DIAMOND_UP_BOX);
        o->color(FL_BACKGROUND2_COLOR);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Metallurgia);
      } // Fl_Round_Button* o
      { grp_voti = new Fl_Group(185, 15, 55, 215);
        { val_voto1 = new Fl_Value_Output(225, 20, 15, 15);
          val_voto1->box(FL_FLAT_BOX);
          val_voto1->color(FL_BACKGROUND2_COLOR);
          val_voto1->textfont(5);
        } // Fl_Value_Output* val_voto1
        { val_voto2 = new Fl_Value_Output(225, 44, 15, 15);
          val_voto2->box(FL_FLAT_BOX);
          val_voto2->color(FL_BACKGROUND2_COLOR);
          val_voto2->textfont(5);
        } // Fl_Value_Output* val_voto2
        { val_voto3 = new Fl_Value_Output(225, 68, 15, 15);
          val_voto3->box(FL_FLAT_BOX);
          val_voto3->color(FL_BACKGROUND2_COLOR);
          val_voto3->textfont(5);
        } // Fl_Value_Output* val_voto3
        { val_voto4 = new Fl_Value_Output(225, 93, 15, 15);
          val_voto4->box(FL_FLAT_BOX);
          val_voto4->color(FL_BACKGROUND2_COLOR);
          val_voto4->textfont(5);
        } // Fl_Value_Output* val_voto4
        { val_voto5 = new Fl_Value_Output(225, 117, 15, 15);
          val_voto5->box(FL_FLAT_BOX);
          val_voto5->color(FL_BACKGROUND2_COLOR);
          val_voto5->textfont(5);
        } // Fl_Value_Output* val_voto5
        { val_voto6 = new Fl_Value_Output(225, 141, 15, 15);
          val_voto6->box(FL_FLAT_BOX);
          val_voto6->color(FL_BACKGROUND2_COLOR);
          val_voto6->textfont(5);
        } // Fl_Value_Output* val_voto6
        { val_voto7 = new Fl_Value_Output(225, 166, 15, 15);
          val_voto7->box(FL_FLAT_BOX);
          val_voto7->color(FL_BACKGROUND2_COLOR);
          val_voto7->textfont(5);
        } // Fl_Value_Output* val_voto7
        { val_voto8 = new Fl_Value_Output(225, 190, 15, 15);
          val_voto8->box(FL_FLAT_BOX);
          val_voto8->color(FL_BACKGROUND2_COLOR);
          val_voto8->textfont(5);
        } // Fl_Value_Output* val_voto8
        { val_voto9 = new Fl_Value_Output(225, 215, 15, 15);
          val_voto9->box(FL_FLAT_BOX);
          val_voto9->color(FL_BACKGROUND2_COLOR);
          val_voto9->textfont(5);
        } // Fl_Value_Output* val_voto9
        grp_voti->end();
      } // Fl_Group* grp_voti
      { scuola_val_media = new Fl_Value_Output(195, 250, 35, 25, " MEDIA SCOLASTICA ");
        scuola_val_media->box(FL_FLAT_BOX);
        scuola_val_media->color(FL_BACKGROUND2_COLOR);
        scuola_val_media->labelfont(5);
        scuola_val_media->textfont(5);
        scuola_val_media->textsize(15);
      } // Fl_Value_Output* scuola_val_media
      { Fl_Box* o = new Fl_Box(75, 240, 105, 5);
        o->box(FL_FLAT_BOX);
        o->color((Fl_Color)48);
      } // Fl_Box* o
      o->end();
    } // Fl_Group* o
    { grp_barrastato = new Fl_Group(10, 290, 405, 45);
      grp_barrastato->box(FL_ENGRAVED_FRAME);
      grp_barrastato->labelsize(10);
      grp_barrastato->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      { Fl_Value_Output* o = scuola_val_soldi = new Fl_Value_Output(65, 300, 125, 25, "Soldi  L.");
        scuola_val_soldi->color(FL_BACKGROUND2_COLOR);
        scuola_val_soldi->labelsize(12);
        if (euro) o->label("Soldi  €");
      } // Fl_Value_Output* scuola_val_soldi
      { scuola_val_rep = new Fl_Value_Output(370, 300, 35, 25, "Reputazione");
        scuola_val_rep->color(FL_BACKGROUND2_COLOR);
        scuola_val_rep->labelsize(12);
      } // Fl_Value_Output* scuola_val_rep
      { scuola_val_studio = new Fl_Value_Output(370, 300, 35, 25, "Studio");
        scuola_val_studio->color(FL_BACKGROUND2_COLOR);
        scuola_val_studio->labelsize(12);
        scuola_val_studio->hide();
      } // Fl_Value_Output* scuola_val_studio
      grp_barrastato->end();
    } // Fl_Group* grp_barrastato
    { Fl_Box* o = new Fl_Box(270, 10, 270, 150, "Immagine inutile");
      o->box(FL_EMBOSSED_FRAME);
    } // Fl_Box* o
    materia_selezionata=1;
    AggiornaScuola();
    win_scuola->size_range(550, 330, 550, 330);
    win_scuola->end();
  } // Fl_Double_Window* win_scuola
  return win_scuola;
}
