// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUIScooter_h
#define GUIScooter_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_scooter;
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>
extern Fl_Output *sco_txtnome;
Fl_Double_Window* GUIScooter();
#endif
