// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUIScooter.h"
#include <FL/Fl.H>
#include <FL/fl_ask.H>
#include "GUITabboz.h"
#include "GUIConcessionario.h"
#include "../zarrosim.h"
#include "../calendario.h"
#include "../sound.h"
#include "../scooter.h"

Fl_Double_Window *win_scooter=(Fl_Double_Window *)0;

static void cb_Concessionario(Fl_Button*, void*) {
  if (x_vacanza != 2) {
  GUIConcessionario();
  win_conce->show();
  win_scooter->deactivate();
}else {
  fl_message_title("Concessionario chiuso");
  fl_alert("Oh, tip%c... oggi il concessionario è chiuso...",ao);
};
}

static void cb_Back(Fl_Return_Button*, void*) {
  win_principale->activate();
AggiornaPrincipale();
win_scooter->hide();
}

Fl_Button *scooter_btn_usa=(Fl_Button *)0;

static void cb_scooter_btn_usa(Fl_Button* o, void*) {
  if(ParcheggiaScooter())
  o->label("Usa scooter");
else
  o->label("Parcheggia scooter");
o->redraw();
AggiornaScooter();
}

static void cb_Fai(Fl_Button*, void*) {
  FaiBenza();
}

static void cb_Ripara(Fl_Button*, void*) {
  RiparaScooter();
}

Fl_Output *sco_txt_nome=(Fl_Output *)0;

Fl_Output *sco_txt_speed=(Fl_Output *)0;

Fl_Output *sco_txt_cc=(Fl_Output *)0;

Fl_Output *sco_txt_stato=(Fl_Output *)0;

Fl_Output *sco_txt_benza=(Fl_Output *)0;

Fl_Value_Output *sco_val_soldi=(Fl_Value_Output *)0;

Fl_Double_Window* GUIScooter() {
  { win_scooter = new Fl_Double_Window(510, 250, "Scooter");
    win_scooter->color(FL_LIGHT3);
    win_scooter->labelfont(1);
    win_scooter->labelsize(12);
    win_scooter->hotspot(win_scooter);
    { Fl_Button* o = new Fl_Button(10, 20, 240, 35, "Concessionario");
      o->callback((Fl_Callback*)cb_Concessionario);
    } // Fl_Button* o
    { Fl_Return_Button* o = new Fl_Return_Button(190, 190, 60, 50, "Back");
      o->callback((Fl_Callback*)cb_Back);
    } // Fl_Return_Button* o
    { scooter_btn_usa = new Fl_Button(10, 95, 240, 35, "Parcheggia scooter");
      scooter_btn_usa->callback((Fl_Callback*)cb_scooter_btn_usa);
      if(ScooterData.attivita==4) { scooter_btn_usa->label("Usa scooter"); scooter_btn_usa->redraw(); }
    } // Fl_Button* scooter_btn_usa
    { Fl_Button* o = new Fl_Button(10, 135, 240, 35, "Fai benza");
      o->callback((Fl_Callback*)cb_Fai);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(260, 175, 240, 30, "Elabora Scooter");
      o->deactivate();
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(260, 210, 240, 30, "Ripara Scooter");
      o->callback((Fl_Callback*)cb_Ripara);
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(260, 20, 240, 150, "Parametri Scooter");
      o->box(FL_EMBOSSED_FRAME);
      o->labelfont(1);
      o->labelsize(12);
      { sco_txt_nome = new Fl_Output(275, 30, 215, 25);
        sco_txt_nome->box(FL_NO_BOX);
      } // Fl_Output* sco_txt_nome
      { sco_txt_speed = new Fl_Output(345, 65, 150, 25, "Velocit\303\240   ");
        sco_txt_speed->box(FL_ENGRAVED_FRAME);
      } // Fl_Output* sco_txt_speed
      { sco_txt_cc = new Fl_Output(345, 90, 150, 25, "Cilindrata ");
        sco_txt_cc->box(FL_ENGRAVED_FRAME);
      } // Fl_Output* sco_txt_cc
      { sco_txt_stato = new Fl_Output(345, 115, 150, 25, "Efficienza ");
        sco_txt_stato->box(FL_ENGRAVED_FRAME);
      } // Fl_Output* sco_txt_stato
      { sco_txt_benza = new Fl_Output(345, 140, 150, 25, "Benzina   ");
        sco_txt_benza->box(FL_ENGRAVED_FRAME);
      } // Fl_Output* sco_txt_benza
      o->end();
    } // Fl_Group* o
    { sco_val_soldi = new Fl_Value_Output(65, 201, 115, 24, "Soldi L.");
      sco_val_soldi->step(1);
      sco_val_soldi->textfont(5);
    } // Fl_Value_Output* sco_val_soldi
    AggiornaScooter();
    win_scooter->set_modal();
    win_scooter->size_range(510, 250, 510, 250);
    win_scooter->end();
  } // Fl_Double_Window* win_scooter
  return win_scooter;
}
