// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUIScooter_h
#define GUIScooter_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_scooter;
#include <FL/Fl_Button.H>
extern Fl_Button *scooter_btn_usa;
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>
extern Fl_Output *sco_txt_nome;
extern Fl_Output *sco_txt_speed;
extern Fl_Output *sco_txt_cc;
extern Fl_Output *sco_txt_stato;
extern Fl_Output *sco_txt_benza;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *sco_val_soldi;
#include <FL/Fl_Return_Button.H>
Fl_Double_Window* GUIScooter();
#endif
