// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUIScuola.h"
int materia_selezionata; 
#include "GUITabboz.h"

Fl_Double_Window *win_scuola=(Fl_Double_Window *)0;

static void cb_OK(Fl_Return_Button*, void*) {
  win_principale->show();
win_scuola->hide();
}

static void cb_Agraria(Fl_Round_Button*, void*) {
  materia_selezionata=1;
}

static void cb_Fisica(Fl_Round_Button*, void*) {
  materia_selezionata=2;
}

static void cb_Attivit(Fl_Round_Button*, void*) {
  materia_selezionata=3;
}

static void cb_Attivit1(Fl_Round_Button*, void*) {
  materia_selezionata=4;
}

static void cb_Scienze(Fl_Round_Button*, void*) {
  materia_selezionata=5;
}

static void cb_Elettrochimica(Fl_Round_Button*, void*) {
  materia_selezionata=6;
}

static void cb_Petrolchimica(Fl_Round_Button*, void*) {
  materia_selezionata=7;
}

static void cb_Filosofia(Fl_Round_Button*, void*) {
  materia_selezionata=8;
}

static void cb_Metallurgia(Fl_Round_Button*, void*) {
  materia_selezionata=9;
}

Fl_Output *tbz_voto1=(Fl_Output *)0;

Fl_Output *tbz_voto2=(Fl_Output *)0;

Fl_Output *tbz_voto3=(Fl_Output *)0;

Fl_Output *tbz_voto4=(Fl_Output *)0;

Fl_Output *tbz_voto5=(Fl_Output *)0;

Fl_Output *tbz_voto6=(Fl_Output *)0;

Fl_Output *tbz_voto7=(Fl_Output *)0;

Fl_Output *tbz_voto8=(Fl_Output *)0;

Fl_Output *tbz_voto9=(Fl_Output *)0;

Fl_Double_Window* GUITabbozScuola() {
  { win_scuola = new Fl_Double_Window(550, 330, "Scuola");
    { Fl_Return_Button* o = new Fl_Return_Button(485, 265, 60, 60, "OK");
      o->callback((Fl_Callback*)cb_OK);
    } // Fl_Return_Button* o
    { new Fl_Button(240, 170, 300, 20, "Studia");
    } // Fl_Button* o
    { new Fl_Button(240, 195, 300, 20, "Corrompi il prof di Attivit\303\240 Matematiche");
    } // Fl_Button* o
    { new Fl_Button(240, 220, 300, 20, "Minaccia");
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(10, 10, 275, 225);
      { Fl_Round_Button* o = new Fl_Round_Button(12, 20, 200, 15, "Agraria...............");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Agraria);
        o->set();
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 43, 200, 15, "Fisica................");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Fisica);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 67, 200, 15, "Attivit\303\240 Culturali....");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Attivit);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 91, 200, 15, "Attivit\303\240 Matematiche..");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Attivit1);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 115, 200, 15, "Scienze Industriali...");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Scienze);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 138, 200, 15, "Elettrochimica........");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Elettrochimica);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 162, 200, 15, "Petrolchimica.........");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Petrolchimica);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 186, 200, 15, "Filosofia Aziendale...");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Filosofia);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(12, 210, 200, 15, "Metallurgia...........");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(5);
        o->callback((Fl_Callback*)cb_Metallurgia);
      } // Fl_Round_Button* o
      { tbz_voto1 = new Fl_Output(210, 15, 15, 24, "output:");
        tbz_voto1->box(FL_NO_BOX);
        tbz_voto1->labeltype(FL_NO_LABEL);
        tbz_voto1->textfont(6);
      } // Fl_Output* tbz_voto1
      { tbz_voto2 = new Fl_Output(210, 38, 15, 24, "output:");
        tbz_voto2->box(FL_NO_BOX);
        tbz_voto2->labeltype(FL_NO_LABEL);
        tbz_voto2->textfont(6);
      } // Fl_Output* tbz_voto2
      { tbz_voto3 = new Fl_Output(210, 62, 15, 24, "output:");
        tbz_voto3->box(FL_NO_BOX);
        tbz_voto3->labeltype(FL_NO_LABEL);
        tbz_voto3->textfont(6);
      } // Fl_Output* tbz_voto3
      { tbz_voto4 = new Fl_Output(210, 86, 15, 24, "output:");
        tbz_voto4->box(FL_NO_BOX);
        tbz_voto4->labeltype(FL_NO_LABEL);
        tbz_voto4->textfont(6);
      } // Fl_Output* tbz_voto4
      { tbz_voto5 = new Fl_Output(210, 110, 15, 24, "output:");
        tbz_voto5->box(FL_NO_BOX);
        tbz_voto5->labeltype(FL_NO_LABEL);
        tbz_voto5->textfont(6);
      } // Fl_Output* tbz_voto5
      { tbz_voto6 = new Fl_Output(210, 133, 15, 24, "output:");
        tbz_voto6->box(FL_NO_BOX);
        tbz_voto6->labeltype(FL_NO_LABEL);
        tbz_voto6->textfont(6);
      } // Fl_Output* tbz_voto6
      { tbz_voto7 = new Fl_Output(210, 157, 15, 24, "output:");
        tbz_voto7->box(FL_NO_BOX);
        tbz_voto7->labeltype(FL_NO_LABEL);
        tbz_voto7->textfont(6);
      } // Fl_Output* tbz_voto7
      { tbz_voto8 = new Fl_Output(210, 181, 15, 24, "output:");
        tbz_voto8->box(FL_NO_BOX);
        tbz_voto8->labeltype(FL_NO_LABEL);
        tbz_voto8->textfont(6);
      } // Fl_Output* tbz_voto8
      { tbz_voto9 = new Fl_Output(210, 205, 15, 24, "output:");
        tbz_voto9->box(FL_NO_BOX);
        tbz_voto9->labeltype(FL_NO_LABEL);
        tbz_voto9->textfont(6);
      } // Fl_Output* tbz_voto9
      o->end();
    } // Fl_Group* o
    materia_selezionata=1;
    win_scuola->set_modal();
    win_scuola->size_range(550, 330, 550, 330);
    win_scuola->end();
  } // Fl_Double_Window* win_scuola
  return win_scuola;
}
