// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUIScuola_h
#define GUIScuola_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_scuola;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
extern Fl_Group *grp_voti;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *val_voto1;
extern Fl_Value_Output *val_voto2;
extern Fl_Value_Output *val_voto3;
extern Fl_Value_Output *val_voto4;
extern Fl_Value_Output *val_voto5;
extern Fl_Value_Output *val_voto6;
extern Fl_Value_Output *val_voto7;
extern Fl_Value_Output *val_voto8;
extern Fl_Value_Output *val_voto9;
extern Fl_Group *grp_barrastato;
extern Fl_Value_Output *val_soldi;
extern Fl_Value_Output *val_rep;
extern Fl_Value_Output *val_studio;
#include <FL/Fl_Box.H>
Fl_Double_Window* GUITabbozScuola();
#endif
