// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUITabacchi_h
#define GUITabacchi_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_tabacchi;
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern Fl_Button *tabac_btn_1;
#include <FL/Fl_Box.H>
extern Fl_Box *tabac_txt_nomesizze;
extern Fl_Box *tabac_txt_descsizze;
extern Fl_Box *tabac_txt_prezzosizze;
#include <FL/Fl_Value_Output.H>
extern Fl_Button *tabac_btn_compra;
#include <FL/Fl_Return_Button.H>
Fl_Double_Window* GUITabacchi();
#endif
