// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUITabboz_h
#define GUITabboz_h
#include <FL/Fl.H>
extern int scelta_gui; 
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_principale;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
extern Fl_Box *main_box_figurino;
extern Fl_Box *main_box_nome;
extern Fl_Box *main_box_giorno;
extern Fl_Button *btn_fastfw;
#include <FL/Fl_Output.H>
extern Fl_Output *main_txtbox_tipa;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *main_valbox_rapporti;
extern Fl_Value_Output *main_valbox_soldi;
extern Fl_Value_Output *main_valbox_paghetta;
extern Fl_Value_Output *main_valbox_stipendio;
extern Fl_Value_Output *main_valbox_rep;
extern Fl_Value_Output *main_valbox_fama;
extern Fl_Value_Output *main_valbox_studio;
extern Fl_Box *main_fig_scarpe;
extern Fl_Box *main_fig_panta;
extern Fl_Box *main_fig_giub;
extern Fl_Box *main_fig_testa;
Fl_Double_Window* GUITabboz();
extern Fl_Menu_Item menu_[];
#endif
