// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUITelefonia_h
#define GUITelefonia_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_telefonia;
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>
extern Fl_Output *tel_txt_nome;
extern Fl_Output *tel_txt_abb;
extern Fl_Output *tel_txt_credito;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *tel_val_soldi;
#include <FL/Fl_Return_Button.H>
Fl_Double_Window* GUITelefonia();
extern Fl_Double_Window *win_compracell;
#include <FL/Fl_Browser.H>
extern Fl_Button *negcell_btn_compra;
#include <FL/Fl_Box.H>
extern Fl_Box *negcell_txt_nomecell;
extern Fl_Box *negcell_txt_desccell;
extern Fl_Box *negcell_txt_prezzocell;
Fl_Double_Window* GUICompraCell();
extern Fl_Double_Window *win_ricaricacell;
#include <FL/Fl_Round_Button.H>
extern Fl_Button *negricarica_btn_compra;
Fl_Double_Window* GUIRicaricaCell();
#endif
