// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUITestbed_h
#define GUITestbed_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_testbed;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Box.H>
extern Fl_Box *box_1;
extern Fl_Box *box_2;
extern Fl_Box *box_3;
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
extern Fl_Button *but_essenza;
extern Fl_Button *but_essenza2;
extern Fl_Button *but_essenza3;
#include <FL/Fl_Value_Input.H>
Fl_Double_Window* GUITestbed();
#endif
