// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUITabboz_h
#define GUITabboz_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_principale;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern Fl_Button *btn_scuola;
#include <FL/Fl_Box.H>
extern Fl_Box *box_figurino;
#include <FL/Fl_Output.H>
extern Fl_Output *out_nome;
extern Fl_Output *out_soldi;
Fl_Double_Window* GUITabboz();
#endif
