// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "GUITestbed.h"
#include "GUITabboz.h"
#include "../zarrosim.h"
#include <FL/Fl_Shared_Image.H>
#include <FL/Fl_PNG_Image.H>

Fl_Double_Window *win_testbed=(Fl_Double_Window *)0;

static void cb_Back(Fl_Return_Button*, void*) {
  win_principale->activate();
AggiornaPrincipale();
win_testbed->hide();
}

Fl_Box *box_1=(Fl_Box *)0;

Fl_Box *box_2=(Fl_Box *)0;

Fl_Box *box_3=(Fl_Box *)0;

static void cb_caricapics(Fl_Button*, void*) {
  //Fl_PNG_Image("provatesta",testa_0,413);
//Fl_PNG_Image("provagiacca",giubbotto_0,sizeof(giubbotto_0));
//Fl_PNG_Image("metallaro",metallaro,18984);

Fl_Shared_Image *sh_img = Fl_Shared_Image::get("res/pic/giubbotto_0.png");

box_1->image(sh_img);

box_1->label(NULL);
box_1->redraw();
win_testbed->redraw();
}

Fl_Double_Window* GUITestbed() {
  { win_testbed = new Fl_Double_Window(836, 656, "TestBed");
    win_testbed->color(FL_LIGHT3);
    win_testbed->hotspot(win_testbed);
    { Fl_Return_Button* o = new Fl_Return_Button(765, 590, 60, 50, "Back");
      o->callback((Fl_Callback*)cb_Back);
    } // Fl_Return_Button* o
    { box_1 = new Fl_Box(10, 10, 455, 570, "box_1");
      box_1->box(FL_ENGRAVED_FRAME);
      box_1->labelsize(16);
      box_1->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* box_1
    { box_2 = new Fl_Box(470, 10, 350, 260, "box_2");
      box_2->box(FL_ENGRAVED_FRAME);
      box_2->labelsize(16);
      box_2->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* box_2
    { box_3 = new Fl_Box(470, 275, 350, 305, "box_3");
      box_3->box(FL_ENGRAVED_FRAME);
      box_3->labelsize(16);
      box_3->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* box_3
    { Fl_Button* o = new Fl_Button(10, 595, 100, 30, "caricapics");
      o->callback((Fl_Callback*)cb_caricapics);
    } // Fl_Button* o
    win_testbed->set_modal();
    win_testbed->size_range(836, 656, 836, 656);
    win_testbed->end();
  } // Fl_Double_Window* win_testbed
  return win_testbed;
}
